up

diff --git a/bin/ctidy b/bin/ctidy
--- a/bin/ctidy
+++ b/bin/ctidy
@@ -1,9 +1,13 @@
 #!/bin/bash
 
+err_echo() {
+	echo "$@" >&2
+}
+
 # Ensure an argument is provided
 if [[ -z "$1" ]]; then
-    echo "Usage: ctidy <filename (without .cpp)> [optional flags]" >&2
-    exit 1
+	echo "Usage: ctidy <filename (without .cpp)> [optional flags]" >&2
+	exit 1
 fi
 
 filename="$1.cpp"
@@ -11,20 +15,20 @@ output="$1"
 
 # Check if the file exists
 if [[ ! -f "$filename" ]]; then
-    echo "Error: File '$filename' not found!" >&2
-    exit 1
+	echo "Error: File '$filename' not found!" >&2
+	exit 1
 fi
 
 todo_lines=$(grep -n "TODO" "$filename" | sed 's/^[0-9]*: *//')
 if [[ -n "$todo_lines" ]]; then
-    echo "$todo_lines" >&2
-    echo -e "\e[31mWarning:\e[0m still found in ${filename}." >&2
-    echo "" >&2
+	echo "$todo_lines" >&2
+	echo -e "\e[31mWarning:\e[0m still found in ${filename}." >&2
+	echo "" >&2
 fi
 
 extra_flags=""
 for arg in "${@:2}"; do
-    extra_flags="$extra_flags $arg"
+	extra_flags="$extra_flags $arg"
 done
 
 echo "Syntax checking $filename with C++20." >&2
