up

diff --git a/bin/run b/bin/run
--- a/bin/run
+++ b/bin/run
@@ -8,9 +8,10 @@ usage() {
 	err_echo "Usage: run [options] <source_file (without .cpp)> [flags]"
 	err_echo ""
 	err_echo "Options:"
-	err_echo "  -t, --time      Measure and display the runtime"
-	err_echo "  -g, --gdb       Debug with GNU Debugger"
-	err_echo "  -d, --debug     Enable DEBUG macro"
+	err_echo "  -t, --time      Measure and display the runtime."
+	err_echo "  -g, --gdb       Debug with GNU Debugger."
+	err_echo "  -d, --debug     Enable DEBUG macro."
+	err_echo " 	-s, --samples	Run with generated samples (.in) then comparing with expected outputs (.out)."
 	err_echo ""
 	err_echo "Flags:"
 	err_echo "  Any additional flags will be passed directly to g++ compilation."
@@ -87,6 +88,31 @@ run() {
 
 	_commands+=("./$_output_file")
 	eval "${_commands[*]}"
+}
+
+run_with_tc() {
+	local _input_file="$1"
+	local _output_file="${_input_file%.in}.out"
+
+	if [[ -z "$_input_file" ]]; then
+		err_echo "Error: No input file provided!"
+		exit 1
+	fi
+	if [[ -z "$_output_file" ]]; then
+		err_echo "Error: No output file provided!"
+		exit 1
+	fi
+
+	if [[  ! "$_input_file" =~ ^.+\.in$ || ! -f "$_input_file" ]]; then
+		err_echo "Error: File '$_input_file' is invalid!"
+		exit 1
+	fi
+	if [[  ! "$_output_file" =~ ^.+\.out$ || ! -f "$_output_file" ]]; then
+		err_echo "Error: File '$_output_file' is invalid!"
+		exit 1
+	fi
+
+	
 }
 
 commands=()
diff --git a/bin/run_s b/bin/run_s
--- a/bin/run_s
+++ b/bin/run_s
@@ -1,9 +1,22 @@
 #!/bin/bash
 
+err_echo() {
+	echo "$@" >&2
+}
+
+usage() {
+	err_echo "Usage: gen <testcase name>"
+	exit 1
+}
+
+if [[ $# -lt 1 ]]; then
+	usage
+fi
+
 # Ensure an argument is provided
 if [[ -z "$1" ]]; then
-    echo "Usage: run_s <filename (without .cpp)> [optional flags]" >&2
-    exit 1
+	echo "Usage: run_s <filename (without .cpp)> [optional flags]" >&2
+	exit 1
 fi
 
 filename="$1.cpp"
@@ -13,20 +26,20 @@ total=0
 
 # Check if the file exists
 if [[ ! -f "$filename" ]]; then
-    echo "Error: File '$filename' not found!" >&2
-    exit 1
+	echo "Error: File '$filename' not found!" >&2
+	exit 1
 fi
 
 todo_lines=$(grep -n "TODO" "$filename" | sed 's/^[0-9]*: *//')
 if [[ -n "$todo_lines" ]]; then
-    echo "$todo_lines" >&2
-    echo -e "\e[31mWarning:\e[0m still found in ${filename}." >&2
-    echo "" >&2
+	echo "$todo_lines" >&2
+	echo -e "\e[31mWarning:\e[0m still found in ${filename}." >&2
+	echo "" >&2
 fi
 
 extra_flags=""
 for arg in "${@:2}"; do
-    extra_flags="$extra_flags $arg"
+	extra_flags="$extra_flags $arg"
 done
 
 # Compile and run
@@ -34,45 +47,45 @@ g++ -std=c++20 -O2 -Wall -Wextra -o "$output" "$filename" $extra_flags
 
 # Run only if compilation was successful
 if [[ $? -eq 0 ]]; then
-    # Loop through all .in files with the specified prefix
-    for input_file in $output*.in; do
-        if [[ -f "$input_file" ]]; then
-            output_file="${input_file%.in}.out"
+	# Loop through all .in files with the specified prefix
+	for input_file in $output*.in; do
+		if [[ -f "$input_file" ]]; then
+			output_file="${input_file%.in}.out"
 
-            ((total++))
+			((total++))
 
-            if [[ ! -f "$output_file" ]]; then
-                echo -e "\e[31mExpected $output_file for $input_file not found. Skipping.\e[0m" >&2
-                ((failed++))
-                continue
-            fi
+			if [[ ! -f "$output_file" ]]; then
+				echo -e "\e[31mExpected $output_file for $input_file not found. Skipping.\e[0m" >&2
+				((failed++))
+				continue
+			fi
 
-            # Run the program and capture its output
-            program_output=$(./"$output" < "$input_file" 2>/dev/null)
-            expected_output=$(cat "$output_file")
+			# Run the program and capture its output
+			program_output=$(./"$output" <"$input_file" 2>/dev/null)
+			expected_output=$(cat "$output_file")
 
-            if [[ "$program_output" != "$expected_output" ]]; then
-                echo "------------------------------------" >&2
-                echo "Test failed for $input_file!" >&2
-                echo "----------" >&2
-                echo "Expected:" >&2
-                echo "$expected_output" >&2
-                echo "----------" >&2
-                echo "Got:" >&2
-                echo "$program_output" >&2
-                echo "------------------------------------" >&2
-                ((failed++))
-            fi
-        fi
-    done
+			if [[ "$program_output" != "$expected_output" ]]; then
+				echo "------------------------------------" >&2
+				echo "Test failed for $input_file!" >&2
+				echo "----------" >&2
+				echo "Expected:" >&2
+				echo "$expected_output" >&2
+				echo "----------" >&2
+				echo "Got:" >&2
+				echo "$program_output" >&2
+				echo "------------------------------------" >&2
+				((failed++))
+			fi
+		fi
+	done
 
-    echo "" >&2
-    if ((failed == 0)); then
-        echo -e "\e[1m\e[32mAll tests passed.\e[0m" >&2
-    else
-        echo -e "\e[1m\e[31m$(($total - $failed)) / $total tests passed.\e[0m" >&2
-    fi
+	echo "" >&2
+	if ((failed == 0)); then
+		echo -e "\e[1m\e[32mAll tests passed.\e[0m" >&2
+	else
+		echo -e "\e[1m\e[31m$(($total - $failed)) / $total tests passed.\e[0m" >&2
+	fi
 else
-    echo "Compilation failed!" >&2
-    exit 1
+	echo "Compilation failed!" >&2
+	exit 1
 fi
